server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql

# Servirá para mostrar o script SQL que está sendo executado
logging:
  level:
    "[org.hibernate.SQL]": debug
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"
